### PR TITLE
Fix 'same module name: icahost' panic error

### PR DESCRIPTION
**Pull request by lehieuhust**
New error "invalid memory address or nil pointer dereference"

### CODE REVIEW

**Comment by nghuyenthevinh2000** [comment]
is it still a work in progress?

**Comment by nghuyenthevinh2000** [comment]
@levanhieuhust 
please remind me to have a google meet with you on this pr at about 3pm tomorrow

**Comment by lehieuhust** [comment]
@nghuyenthevinh2000

**Comment by lehieuhust** [comment]
still got stuck with error : test panicked: parameter ControllerEnabled not registered
icacontrollertypes was registered in https://github.com/notional-labs/quicksilver/blob/6efcfe735a770623eefd4e100b5c572c43efb092/app/app.go#L1044

**Pull request merged**
